its_commu/its_commu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('info/', TemplateView.as_view(template_name='info.html'), name='info'),
    path('board/', TemplateView.as_view(template_name='board.html'), name='board'),
    path('my/', TemplateView.as_view(template_name='my.html'), name='my'),
    path('recruit/', TemplateView.as_view(template_name='recruit.html'), name='recruit'),
    path('account/', include('django.contrib.auth.urls')),
    path('user/', include('user.urls')),
]

its_commu/user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [
    path('my_setting/', views.my_setting, name='my_setting'),
    path('join/', views.join, name='join'),
    path('login/', auth_views.LoginView.as_view(template_name='login_error.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

its_commu/board/models.py
from django.db import models

# Create your models here.
class Announce(models.Model):
    doc_no = models.CharField(max_length=20, primary_key=True, null=False)
    writer = models.CharField(max_length=50, null=False)
    write_date = models.DateField(null=False)
    viewer = models.IntegerField(default=0, null=False)
    desc = models.CharField(max_length=255)
    insert_date = models.DateField(auto_now_add=True)
    insert_user = models.CharField(max_length=50)
    deleted = models.CharField(max_length=1)
    insert_std = models.CharField(max_length=50, null=False)

    def __str__(self):
        return self.doc_no

its_commu/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>IT's Web</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/common.css' %}" />
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet" href="{% static 'css/login_modal.css' %}" />
    <script src="{% static 'js/base.js' %}"></script>
    <script src="{% static 'js/login_modal.js' %}"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    {% block extra_head %}
    {% endblock %}
</head>
<body>
    <header>
        <div id="header_inner">
            <div class="logo">
                <a href="{% url 'home' %}"><img src="{% static 'images/' %}" alt="아이티스 로고"></a>
            </div>
            <nav>
            {% if user.is_authenticated %}
                <ul>
                    <li><a href="{% url 'info' %}">소개</a></li>
                    <li><a href="{% url 'board' %}">게시판</a></li>
                    <li><a href="{% url 'my' %}">마이페이지</a></li>
                </ul>
            {% else %}
                <ul>
                    <li><a href="{% url 'info' %}">소개</a></li>
                    <li><a href="{% url 'board' %}">게시판</a></li>
                    <li class="login-btn"><button onclick="">로그인</button></li>
                </ul>
            {% endif %}
            </nav>
            {% include 'login_modal.html' %}
        </div>
    </header>
    
    <main>
        <div id="container">
            {% block content %}
            {% endblock %}
        </div>
    </main>
    <footer>
        <div id="footer_inner">
            <p>&copy; 한양여자대학교 소프트웨어융합과 과동아리 아이티스</p>
        </div>
    </footer>
</body>
</html>

its_commu/templates/board.html
{% extends "base.html" %}

{% block extra_head %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/board.css' %}" />
<script src="{% static 'js/board.js' %}"></script>
{% endblock %}

{% block content %}
<!--메인 콘텐츠 작성-->
<div class="board">
<aside>
    <div class="menuA"><a href="">공지사항</a></div>
    <div class="menuB"><a href="">문의하기</a></div>
    <div class="menuC">
        <i class="bi bi-chevron-right"></i>
        <a href="">커뮤니티</a>
    </div>
</aside>

<div class="post">
    <div class="postA">
        <span class="postA1">총 <span class="post-count">99</span>개</span>
        <div class="postA2">
            <input class="post-search" type="search" placeholder="검색어를 입력해 주세요">
            <i class="bi bi-search"></i>
        </div>
    </div>
    
    <div class="postB">
        <div class="postB1">01</div>
        <div class="postB2">
            <div class="post_title">5월 정기 발표회 안내</div>
            <div class="post_info"><span class="name">김나리</span>
            &nbsp|&nbsp
            <span class="date">2025.01.01</span>
            &nbsp|&nbsp
            <span class="click_text">조회수&nbsp</span>
            <span class="click">15</span></div>
        </div>
    </div>    

    <div class="postB">
        <div class="postB1">01</div>
        <div class="postB2">
            <div class="post_title">5월 정기 발표회 안내</div>
            <div class="post_info"><span class="name">김나리</span>
            &nbsp|&nbsp
            <span class="date">2025.01.01</span>
            &nbsp|&nbsp
            <span class="click_text">조회수&nbsp</span>
            <span class="click">15</span></div>
        </div>
    </div> 

    <div class="postB">
        <div class="postB1">01</div>
        <div class="postB2">
            <div class="post_title">5월 정기 발표회 안내</div>
            <div class="post_info"><span class="name">김나리</span>
            &nbsp|&nbsp
            <span class="date">2025.01.01</span>
            &nbsp|&nbsp
            <span class="click_text">조회수&nbsp</span>
            <span class="click">15</span></div>
        </div>
    </div> 

    <div class="postB">
        <div class="postB1">01</div>
        <div class="postB2">
            <div class="post_title">5월 정기 발표회 안내</div>
            <div class="post_info"><span class="name">김나리</span>
            &nbsp|&nbsp
            <span class="date">2025.01.01</span>
            &nbsp|&nbsp
            <span class="click_text">조회수&nbsp</span>
            <span class="click">15</span></div>
        </div>
    </div> 

    <div class="postB">
        <div class="postB1">01</div>
        <div class="postB2">
            <div class="post_title">5월 정기 발표회 안내</div>
            <div class="post_info"><span class="name">김나리</span>
            &nbsp|&nbsp
            <span class="date">2025.01.01</span>
            &nbsp|&nbsp
            <span class="click_text">조회수&nbsp</span>
            <span class="click">15</span></div>
        </div>
    </div> 

    <div class="postB">
        <div class="postB1">01</div>
        <div class="postB2">
            <div class="post_title">5월 정기 발표회 안내</div>
            <div class="post_info"><span class="name">김나리</span>
            &nbsp|&nbsp
            <span class="date">2025.01.01</span>
            &nbsp|&nbsp
            <span class="click_text">조회수&nbsp</span>
            <span class="click">15</span></div>
        </div>
    </div> 

    <div class="postB">
        <div class="postB1">01</div>
        <div class="postB2">
            <div class="post_title">5월 정기 발표회 안내</div>
            <div class="post_info"><span class="name">김나리</span>
            &nbsp|&nbsp
            <span class="date">2025.01.01</span>
            &nbsp|&nbsp
            <span class="click_text">조회수&nbsp</span>
            <span class="click">15</span></div>
        </div>
    </div> 

    <div class="postB">
        <div class="postB1">01</div>
        <div class="postB2">
            <div class="post_title">5월 정기 발표회 안내</div>
            <div class="post_info"><span class="name">김나리</span>
            &nbsp|&nbsp
            <span class="date">2025.01.01</span>
            &nbsp|&nbsp
            <span class="click_text">조회수&nbsp</span>
            <span class="click">15</span></div>
        </div>
    </div> 

    <div class="postB">
        <div class="postB1">01</div>
        <div class="postB2">
            <div class="post_title">5월 정기 발표회 안내</div>
            <div class="post_info"><span class="name">김나리</span>
            &nbsp|&nbsp
            <span class="date">2025.01.01</span>
            &nbsp|&nbsp
            <span class="click_text">조회수&nbsp</span>
            <span class="click">15</span></div>
        </div>
    </div> 

    <div class="postB">
        <div class="postB1">01</div>
        <div class="postB2">
            <div class="post_title">5월 정기 발표회 안내</div>
            <div class="post_info"><span class="name">김나리</span>
            &nbsp|&nbsp
            <span class="date">2025.01.01</span>
            &nbsp|&nbsp
            <span class="click_text">조회수&nbsp</span>
            <span class="click">15</span></div>
        </div>
    </div> 

    <div class="page">
        <ul>
            <li><a href=""><i class="bi bi-chevron-left"></i></a></li>
            <li><a href="">1</a></li>
            <li><a href="">2</a></li>
            <li><a href="">3</a></li>
            <li><a href="">4</a></li>
            <li><a href="">5</a></li>
            <li><a href=""><i class="bi bi-chevron-right"></i></a></li>
        </ul>
    </div>
</div>

</div>

{% endblock %}

its_commu/templates/home.html
{% extends "base.html" %}

{% block extra_head %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/home.css' %}" />
  <script src="{% static 'js/home.js' %}"></script>
{% endblock %}

{% block content %}
  <div class="visual">
    <div class="visual-text">
      <h2>한양여자대학교 소프트웨어융합과 과동아리</h2>
      <h1>IT's 아이티스</h1>
    </div>
    <div class="visual-circle">
      <div class="circle circleA">
        <h2>PROJECT</h2>
      </div>
      <div class="circle circleB">
        <h2>PRESENTATION</h2>
      </div>
      <div class="circle circleC">
        <h2>CERTIFICATE</h2>
      </div>
      <div class="circle circleD">
        <h2>STUDY</h2>
      </div>
    </div>
  </div>
{% endblock %}

its_commu/templates/info.html
{% extends "base.html" %}

{% block extra_head %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/info.css' %}" />
<script src="{% static 'js/info.js' %}"></script>
{% endblock %}

{% block content %}
<!--메인 콘텐츠 작성-->
{% endblock %}

its_commu/templates/join.html
{% extends "base.html" %}

{% block extra_head %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/join.css' %}" />
<script src="{% static 'js/join.js' %}"></script> 
{% endblock %}

{% block content %}
  <div class="title_wrap">
    <span class="title">회원가입</span>
    <hr>
  </div>

  <div class="content_wrap">
    <form id="form_join" method="post" action="">
      <div class="form_list">
        <div class="form_item id">
          <input type="text" name="id" placeholder="아이디" required><br>
          <div>
            <button type="button" class="check-id" onclick="checkID()">중복확인</button>
            <span class="id-status" id="id-Status">사용 가능한 아이디입니다.</span>
          </div>
          
        </div>
        <div class="form_item passwd">
          <input type="password" name="passwd" placeholder="비밀번호" required>
        </div>
        <div class="form_item passwd_ck">
          <input type="password" name="ck_passwd" placeholder="비밀번호 확인" required>
        </div>
      </div>

      <div class="form_list">
        <div class="form_item name">
          <input type="text" name="name" placeholder="이름" required>
        </div>
        <div class="form_item grade">
          <input type="text" name="grade" placeholder="학번" required>
        </div>
        <div class="form_item b_day">
          <input type="date" name="b_day" placeholder="생년월일" required>
        </div>
        <div class="form_item tel">
          <input type="text" name="tel" placeholder="전화번호" required>
        </div>
        <div class="form_item email">
          <input type="email" name="email" placeholder="이메일" required>
        </div>
        <div class="form_item git">
          <input type="text" name="git" placeholder="깃허브 주소" required>
        </div>
      </div>
      
      <div class="form_list">
        <div class="form_select s_grade">
          <label>참여년도 선택</label><br>
          <hr class="line">
          <div class="toggle-button" date-value="2021"><span>#2021</span></div>
          <div class="toggle-button" date-value="2022"><span>#2022</span></div>
          <div class="toggle-button" date-value="2023"><span>#2023</span></div>
          <div class="toggle-button" date-value="2024"><span>#2024</span></div>
          <div class="toggle-button" date-value="2025"><span>#2025</span></div>
        </div>
  
        <div class="form_select s_interest">
          <label>관심분야 선택</label><br>
          <hr class="line">
          <div class="toggle-button" date-value="UIUXDesign"><span>#UIUXDesign</span></div>
          <div class="toggle-button" date-value="Front-End"><span>#Front-End</span></div>
          <div class="toggle-button" date-value="Back-End"><span>#Back-End</span></div>
          <div class="toggle-button" date-value="Network"><span>#Network</span></div>
          <div class="toggle-button" date-value="Cloud"><span>#Cloud</span></div>
          <div class="toggle-button" date-value="Server"><span>#Server</span></div>
          <div class="toggle-button" date-value="Al"><span>#Al</span></div>
          <div class="toggle-button" date-value="IOT"><span>#IOT</span></div>
          <div class="toggle-button" date-value="DevOps"><span>#DevOps</span></div>
        </div>

        <div class="form_select s_skill">
          <label>기술스택 선택</label><br>
          <hr class="line">
          <div class="toggle-button" date-value="C"><span>C</span></div>
          <div class="toggle-button" date-value="Python"><span>Python</span></div>
          <div class="toggle-button" date-value="JAVA"><span>JAVA</span></div>
          <div class="toggle-button" date-value="HTML"><span>HTML</span></div>
          <div class="toggle-button" date-value="CSS"><span>CSS</span></div>
          <div class="toggle-button" date-value="JavaScript"><span>JavaScript</span></div>
          <div class="toggle-button" date-value="Spring"><span>Spring</span></div>
          <div class="toggle-button" date-value="React"><span>React</span></div>
          <div class="toggle-button" date-value="Django"><span>Django</span></div>
          <div class="toggle-button" date-value="R"><span>R</span></div>
        </div>

        <div class="form_item intro">
          <textarea name="intro" id="intro" placeholder="자기소개"></textarea>
        </div>
      </div>
      <button class="sub_btn" type="submit">회원가입</button>
    </form>
  </div>

{% endblock %}

its_commu/templates/login_error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script type="text/javascript">
        alert("로그인 정보가 일치하지 않습니다.")
        location.href = "http://127.0.0.1:8000/"
</script>
</head>
<body>
</body>
</html>

its_commu/templates/login_modal.html
<div id="loginModal" class="modal">
  <div class="modal-content">
      <span class="close">&times;</span>
      <img src="" alt="logo">
      <form method="post" action="{% url 'login' %}">
          {% csrf_token %}
          <input type="text" id="username" name="username" placeholder="아이디" required>
          <input type="password" id="password" name="password" placeholder="비밀번호" required>
          <button type="submit">로그인</button>
      </form>
      <div class="links">
          <a href="#">비밀번호 찾기</a> 
          <a>|</a>
          <a href="#">아이디 찾기</a> 
          <a>|</a>
          <a href="{%url 'account:join' %}">회원가입</a>
      </div>
  </div>
</div>

its_commu/templates/my.html
{% extends "base.html" %}

{% block extra_head %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/my.css' %}" />
<script src="{% static 'js/my.js' %}"></script>
{% endblock %}

{% block content %}
    <div class ="profile">
        <div class="profile-title">
            <h2>프로필</h2>
        </div>
        <div class ="profile-box">
            <div class="profile-member">
                <div class="profile-face">
                    <!-- <div class="user"><img src="{% static 'images/userimg.png' %}" alt="프로필 이미지"></div> -->
                </div>
                <div class="profile-textbox">
                    <div class="profile-text1">
                        <div class="pro-t1"><h1>{{user.username}}</h1></div>
                        <div class="pro-t2"><h1>님 안녕하세요.</h1></div>
                    </div>
                    <div class="profile-text2">
                        <i class="bi bi-box-arrow-right"></i>
                        <form action="{% url 'logout' %}" method="post">
                            {% csrf_token %}
                            <input type="submit" value="로그아웃" />
                        </form><div class="pro-t3"></div>
                        <a href="{% url 'my_setting' %}"><i class="bi bi-gear"></i><div class="pro-t4"><h1>설정</h1></div></a></div>
                    </div>
                </div> 
            </div>
        </div>         
    </div>
    <a href="#">
        <div class ="write">
            <div class="write-title">
                <h2>내가 쓴 글</h2>
                <div class="write-title2">
                    <h1>더보기</h1>
                    <i class="bi bi-plus-circle"></i>
                </div>
            </div>
            <div class ="write-box1">
                <div class="write-text1">
                    <div class="wri-t1"><h1>공지사항</h1></div>
                    <div class="wri-t2"><h1>아이티스 관련 제목입니다</h1></div>
                    <div class="wri-t3"><h1>2024.01.01</h1></div>
                </div> 
            </div>
            <div class ="write-box2">
                <div class="write-text2">
                    <div class="wri-t4"><h1>Q&A</h1></div>
                    <div class="wri-t5"><h1>아이티스 관련 제목입니다</h1></div>
                    <div class="wri-t6"><h1>2024.01.01</h1></div>
                </div> 
            </div>
        </div>
    </a>
    <a href="#">
        <div class ="comment">
            <div class="comment-title">
                <h2>댓글 단 글</h2>
                <div class="comment-title2">
                    <h1>더보기</h1>
                    <i class="bi bi-plus-circle"></i>
                </div>
            </div>
            <div class ="comment-box1">
                <div class="comment-text1">
                    <div class="com-t1"><h1>Q&A</h1></div>
                    <div class="com-t2"><h1>아이티스 관련 제목입니다</h1></div>
                    <div class="com-t3"><h1>2024.01.01</h1></div>
                </div> 
            </div>
        </div>
    </a>
    <a href="#">
        <div class ="like">
            <div class="like-title">
                <h2>좋아요한 글</h2>
                <div class="like-title2">
                    <h1>더보기</h1>
                    <i class="bi bi-plus-circle"></i>
                </div>
            </div>
            <div class ="like-box1">
                <div class="like-text1">
                    <div class="like-t1">
                    <i class="bi bi-exclamation-circle"></i>
                    <h1>좋아요한 글이 없습니다.</h1>
                    </div>
                </div> 
            </div>
        </div>
    </a>
    <a href="#">
        <div class ="bookmark">
            <div class="bookmark-title">
                <h2>내가 쓴 글</h2>
                <div class="bookmark-title2">
                    <h1>더보기</h1>
                    <i class="bi bi-plus-circle"></i>
                </div>
            </div>
            <div class ="bookmark-box1">
                <div class="bookmark-text1">
                    <div class="bmk-t1"><h1>Talk</h1></div>
                    <div class="bmk-t2"><h1>아이티스 관련 제목입니다</h1></div>
                    <div class="bmk-t3"><h1>2024.01.01</h1></div>
                </div> 
            </div>
            <div class ="bookmark-box2">
                <div class="bookmark-text2">
                    <div class="bmk-t4"><h1>Q&A</h1></div>
                    <div class="bmk-t5"><h1>아이티스 관련 제목입니다</h1></div>
                    <div class="bmk-t6"><h1>2024.01.01</h1></div>
                </div> 
            </div>
        </div>
    </a>
{% endblock %}

its_commu/templates/my_setting.html
{% extends "base.html" %}

{% block extra_head %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/my_setting.css' %}" />
<script src="{% static 'js/my_setting.js' %}"></script>
{% endblock %}

{% block content %}
<!--메인 콘텐츠 작성-->
<div class="my_setting">
    <div class ="setting">
        <div class="setting-title">
            <h2>설정</h2>
        </div>
        <!-- <hr> -->
    </div>
    <div class="profile">
        <div class="user"><img src="{% static 'images/userimg.png' %}" alt="프로필 이미지"></div>
    </div>
    <form id="form-setting" method="post" action="">
        <div class="setup">
            <div class="change">
                <div class="change-title" id="modify">
                    <h2>이름</h2>
                </div>
                <input type="text" id="name" name="name" placeholder="홍길동" required>
                <div class="change-title" id="modify">
                    <h2>아이디</h2>
                </div>
                <input type="text" id="username" name="username" placeholder="itslove1234" required>
                <div class="change-title" id="modify">
                    <h2>학번</h2>
                </div>
                <input type="text" id="studentnum" name="studentnum" placeholder="242424" required>
                <div class="change-title" id="modify">
                    <h2>생년월일</h2>
                </div>
                <input type="date" id="date" name="date" placeholder="2024.01.01" required>
                <div class="change-title" id="modify">
                    <h2>전화번호</h2>
                </div>
                <input type="text" id="phonenum" name="phonenum" placeholder="010-1234-5678" required>
                <div class="change-title" id="modify">
                    <h2>이메일</h2>
                </div>
                <input type="email" id="email" name="email" placeholder="이메일" required>
                <div class="change-title" id="modify">
                    <h2>깃허브</h2>
                </div>
                <input type="text" id="github" name="github" placeholder="깃허브주소" required>
                <div class="change-title" id="choice">
                    <h2>참여년도</h2>
                    <div class="change-box">
                        <div class="tags" id="years">
                            <span class="tag">#2024</span>
                            <span class="tag">#2023</span>
                            <span class="tag">#2022</span>
                        </div>
                    </div> 
                </div>
                <div class="change-title" id="choice">
                    <h2>관심분야</h2>
                    <div class="change-box">
                        <div class="tags" id="interests">
                            <span class="tag">#UI/UXDesign</span>
                            <span class="tag">#Front-End</span>
                            <span class="tag">#Back-End</span>
                            <span class="tag">#Network</span>
                            <span class="tag">#Cloud</span>
                            <span class="tag">#Server</span>
                            <span class="tag">#AI</span>
                            <span class="tag">#IOT</span>
                            <span class="tag">#DevOps</span>
                        </div>
                    </div> 
                </div>
                <div class="change-title" id="choice">
                    <h2>기술스택</h2>
                    <div class="change-box">
                        <div class="tags" id="tech-stack">
                            <span class="tag">#C</span>
                            <span class="tag">#Python</span>
                            <span class="tag">#JAVA</span>
                            <span class="tag">#HTML</span>
                            <span class="tag">#CSS</span>
                            <span class="tag">#JavaScript</span>
                            <span class="tag">#Spring</span>
                            <span class="tag">#React</span>
                            <span class="tag">#Django</span>
                            <span class="tag">#R</span>
                        </div>
                    </div>             
                </div>
                <div class="change-title" id="modify">
                    <h2>자기소개</h2>
                </div>
                <input type="text" id="intro" name="intro" placeholder="자기소개" required>
                
            </div>
            <div class="system">
                <div class="sys-content" id="passward">
                    <a href="#">비밀번호 변경</a>
                    <a href="#"><i class="bi bi-chevron-right"></i></a>
                </div>
                <div class="sys-content" id="alarm">
                    <a href="#">알람 설정</a> 
                    <a href="#"><i class="bi bi-chevron-right"></i></a>
                </div>
                <div class="sys-content" id="withdrawal">
                    <a href="#">탈퇴하기</a>
                    <a href="#"><i class="bi bi-chevron-right"></i></a>
                </div>        
            </div>
            <button class="complete" type="submit">완료</button>    
        </div>
    </form> 
</div>



          
         

{% endblock %}

its_commu/templates/recruit.html
{% extends "base.html" %}

{% block extra_head %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/recruit.css' %}" />
<script src="{% static 'js/recruit.js' %}"></script>
{% endblock %}

{% block content %}
<!--메인 콘텐츠 작성-->
{% endblock %}